package model;
// Generated 04/06/2021 17:37:21 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tbpais generated by hbm2java
 */
@Entity
@Table(name="tbpais"
    ,catalog="demobd"
)
public class Tbpais  implements java.io.Serializable {


     private Integer idPais;
     private String nombrePais;

    public Tbpais() {
    }

    public Tbpais(String nombrePais) {
       this.nombrePais = nombrePais;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPais", unique=true, nullable=false)
    public Integer getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }

    
    @Column(name="nombrePais", nullable=false, length=50)
    public String getNombrePais() {
        return this.nombrePais;
    }
    
    public void setNombrePais(String nombrePais) {
        this.nombrePais = nombrePais;
    }




}


